### ISSUE TITLE
运行前端时一直无法进入

### ISSUE THREAD

**Issue by seamusic** [NameIsBad/abp-vue#1]
所有的环境都是默认的。
win10，已运行host。
但在运行前端时，一直无法进入登录界面。

命令行有以下提示：
![image](https://user-images.githubusercontent.com/172009/161441898-726c12e1-526e-4e58-9f64-d94ccb83136f.png)

然后
![image](https://user-images.githubusercontent.com/172009/161441922-2cd68040-9eb2-46c7-b2d2-e1bfd905e4ea.png)

**Comment by NameIsBad** [comment]
可以试下[前端官方的项目](https://github.com/vbenjs/vue-vben-admin/tree/v2.8.0)能不能跑起来
我看到的区别好像是你的vite版本有点高，下图是我运行的情况
![image](https://user-images.githubusercontent.com/7506878/162600115-c3fdf51b-1e87-4daa-aaaa-ed04a492f52f.png)
